### ISSUE TITLE
Amit Kumar Jaiswal: new volunteer via Mozilla Science Lab Collaborate

### ISSUE THREAD

**Issue by amitkumarj441** [acgetchell/CDT-plusplus#16]
Currently I`m working on making efficient calculation of distance using Bellman-Ford algorithms and hence I would like to contribute for this project under 'Implement insertion and calculation of mass'.<p><br><blockquote>This issue was created by @amitkumarj441 via <a href='https://mozillascience.org/collaborate'>Mozilla Science Lab Collaborate</a></blockquote></p>

**Comment by amitkumarj441** [comment]
I went through the whole documentation of CDT-plusplus and and submitted code for finding shortest path, but i did some mistake in naming file name and hence, i initiated a pull request.

**Comment by acgetchell** [comment]
Hi Amit,

Thank you very much for your contribution.

However, as-is I cannot really make use of your patch, as it is not integrated with the main code, nor does it have appropriate unit tests and/or documentation. This isn't your fault, because I hadn't published guidelines, but I do now have them.

Please look them over and restructure your code accordingly. I believe you can make further commits to this pull request, so I'll leave this open. Otherwise, if you just want to redo it you just open another pull request.

**Comment by amitkumarj441** [comment]
Hi @acgetchell ,
Some times back, I initiated a pull request for Shortest path algorithm.
Please have a look into this.

Cheers,
Amit Kumar Jaiswal
